name: adminnut4health
description: NUT4Health Dashboard.

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-253.0.dev <3.0.0'

dependencies:
  cloud_firestore: ^4.8.2
  equatable: ^2.0.5
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.4
  flutter:
    sdk: flutter
  tuple: ^2.0.0
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.7
  go_router: ^5.2.4
  intl: ^0.18.0
  rxdart: ^0.27.7
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.1.11
  path_provider: ^2.0.15
  path_provider_macos: ^2.0.0
  desktop_window: 0.4.0
  shared_preferences: ^2.1.2
  syncfusion_localizations: ^22.1.36
  syncfusion_flutter_datagrid_export: ^22.1.36
  syncfusion_flutter_calendar: ^22.1.36
  syncfusion_flutter_datepicker: ^22.1.36
  syncfusion_flutter_charts: ^22.1.36
  syncfusion_flutter_gauges: ^22.1.36
  syncfusion_flutter_sliders: ^22.1.36
  syncfusion_flutter_pdf: ^22.1.36
  syncfusion_flutter_barcodes: ^22.1.36
  syncfusion_officechart: ^22.1.36
  syncfusion_flutter_maps: ^22.1.36
  syncfusion_flutter_signaturepad: ^22.1.36
  syncfusion_flutter_pdfviewer: ^22.1.36
  syncfusion_flutter_treemap: ^22.1.36
  syncfusion_flutter_core: ^22.1.36
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.5.0
  file_picker: ^5.3.2
  csv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  random_string:
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - images/
    - images/pdf/
    - images/xlsio/
    - images/pdf_viewer/
    - assets/pdf/
    - assets/sample_details.json
    - assets/sample_details_fr.json
    - assets/worldmap.json
    - assets/africa.json
    - assets/europe.json
    - assets/germany.json
    - assets/india.json
    - assets/usa.json
    - assets/south_america.json
    - assets/australia.json
    - assets/maps_brazil_boundary.json
    - assets/maps_uk_boundary.json
    - assets/maps_france_boundary.json
    - assets/river.json
    - assets/london_to_british.json
    - assets/london_to_chessington.json
    - assets/london_to_hampton_court_palace.json
    - assets/london_to_twickenham_stadium.json
    - assets/london_to_windsor_castle.json
    - assets/product_data.json
    - assets/chart_data.json

  fonts:
    - family: HeeboBold
      fonts:
        - asset: assets/fonts/Heebo-Bold.ttf
    - family: HeeboMedium
      fonts:
        - asset: assets/fonts/Heebo-Medium.ttf
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Roboto-Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
