// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDwwcYxHIihPH0sSGDYsoT0nIrO3PyjUMI",
      authDomain: "nut4health-830cc.firebaseapp.com",
      databaseURL: "https://nut4health-830cc.firebaseio.com",
      projectId: "nut4health-830cc",
      storageBucket: "nut4health-830cc.appspot.com",
      messagingSenderId: "1055399108789",
      appId: "1:1055399108789:web:a9533dad5bdf00aadf9efc",
      measurementId: "G-9NXD66C4L6"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJy4cuSKF18zG-O_4UdgC1cqyRtD_Vc9I',
    appId: '1:1055399108789:android:01a77500579a542bdf9efc',
    messagingSenderId: '1055399108789',
    projectId: 'nut4health-830cc',
    databaseURL: 'https://nut4health-830cc.firebaseio.com',
    storageBucket: 'nut4health-830cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuD6d-fiTh0h0ryAgx9D-JBSyhj_SJZDQ',
    appId: '1:1055399108789:ios:170f4812b275e225df9efc',
    messagingSenderId: '1055399108789',
    projectId: 'nut4health-830cc',
    databaseURL: 'https://nut4health-830cc.firebaseio.com',
    storageBucket: 'nut4health-830cc.appspot.com',
    iosClientId: '1055399108789-3hg8vu2bmadftcsfsqpfnbcv47dtibq3.apps.googleusercontent.com',
    iosBundleId: 'org.sic4change.adminnut4health.adminnut4health',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuD6d-fiTh0h0ryAgx9D-JBSyhj_SJZDQ',
    appId: '1:1055399108789:ios:170f4812b275e225df9efc',
    messagingSenderId: '1055399108789',
    projectId: 'nut4health-830cc',
    databaseURL: 'https://nut4health-830cc.firebaseio.com',
    storageBucket: 'nut4health-830cc.appspot.com',
    iosClientId: '1055399108789-3hg8vu2bmadftcsfsqpfnbcv47dtibq3.apps.googleusercontent.com',
    iosBundleId: 'org.sic4change.adminnut4health.adminnut4health',
  );
}
